name: Ping Supabase Weekly

on:
  schedule:
    - cron: '0 12 * * 0'  # Every Sunday at 12:00 UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - name: Curl Supabase
        run: |
          curl -sSf -H "apikey: $SUPABASE_ANON_KEY" https://fducbfbomteiknvfpbbc.supabase.co/health